version: "3.8"

services:
  web: 
    image: truongvovanit/long-la:latest # <-- Đã đổi thành pull từ Hub
    container_name: longla_web
    env_file:
      - .env.production
    expose:
      - "80" 

  caddy:
    image: caddy:alpine
    container_name: caddy_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from long-la.duckdns.org --to web:80
    depends_on:
      - web
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: